### ISSUE TITLE
Build fails on 32 bit arm (option -m64)

### ISSUE THREAD

**Issue by khumarahn** [jvirkki/libbloom#15]
Hi, there seems to be a problem deciding between -m32 or -m64 options in `Makefile` on 32 bit arm:
```
$ make
mkdir -p /home/khu/test/libbloom/build
cc   -Wall -O3 -m64 -std=c99 -fPIC -DBLOOM_VERSION=1.5 -I/home/khu/test/libbloom -I/home/khu/test/libbloom/murmur2 -c murmur2/MurmurHash2.c -o /home/khu/test/libbloom/build/murmurhash2.o
gcc: error: unrecognized command line option ‘-m64’
make: *** [Makefile:117: /home/khu/test/libbloom/build/murmurhash2.o] Error 1
```

**Comment by jvirkki** [comment]
By default it tries to build a 64 bit library.
To build a 32 bit library on most platforms one would run "BITS=32 make".

However, in the case of your compiler which doesn't recognize the 32/64 bit options, this should work:

`BITS=default make`

See the Makefile comments for more documentation on build options.

**Comment by khumarahn** [comment]
Thanks! It works with BITS=default for me.

My compiler is nothing special:
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/armv7a-hardfloat-linux-gnueabi/7.3.0/lto-wrapper
Target: armv7a-hardfloat-linux-gnueabi
Configured with: /var/tmp/portage/sys-devel/gcc-7.3.0-r1/work/gcc-7.3.0/configure --host=armv7a-hardfloat-linux-gnueabi --build=armv7a-hardfloat-linux-gnueabi --prefix=/usr --bindir=/usr/armv7a-hardfloat-linux-gnueabi/gcc-bin/7.3.0 --includedir=/usr/lib/gcc/armv7a-hardfloat-linux-gnueabi/7.3.0/include --datadir=/usr/share/gcc-data/armv7a-hardfloat-linux-gnueabi/7.3.0 --mandir=/usr/share/gcc-data/armv7a-hardfloat-linux-gnueabi/7.3.0/man --infodir=/usr/share/gcc-data/armv7a-hardfloat-linux-gnueabi/7.3.0/info --with-gxx-include-dir=/usr/lib/gcc/armv7a-hardfloat-linux-gnueabi/7.3.0/include/g++-v7 --with-python-dir=/share/gcc-data/armv7a-hardfloat-linux-gnueabi/7.3.0/python --enable-languages=c,c++,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 7.3.0-r1 p1.1' --disable-esp --enable-libstdcxx-time --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --disable-multilib --disable-altivec --disable-fixed-point --with-float=hard --with-arch=armv7-a --with-float=hard --with-fpu=vfpv3-d16 --disable-libgcj --enable-libgomp --disable-libmudflap --disable-libssp --disable-libcilkrts --disable-libmpx --enable-vtable-verify --enable-libvtv --enable-lto --without-isl --enable-libsanitizer --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 7.3.0 (Gentoo 7.3.0-r1 p1.1) 
```

Should we (gentoo) modify the build script, or it makes sense to fix the bits detection upstream? Say, make it use default by default?
```
ifeq ($(BITS),)
MM=
...
```

**Comment by jvirkki** [comment]
I recommend setting the BITS=default either in the compilation environment or the make invocation. I'm not familiar with gentoo package build environment details but hopefully it allows for setting such variables?

I prefer to keep the build interface consistent so I prefer not to change the default, as that would change the behavior for anyone who has been expecting -m64 to be the default as it has been for a long while.

I suggest not patching the Makefile locally as that will just make future version updates more brittle. If for some reason you can't set BITS in the environment, I could add a special makefile target which does the same thing. That way you don't need to carry any local patches. But try setting BITS first, as the most straightforward solution.

**Comment by jvirkki** [comment]
In v2, I removed BITS and the defaults. It will now build as the platform default.
