### ISSUE TITLE
Strong correlation between filter size and real error / collision number

### ISSUE THREAD

**Issue by peko** [jvirkki/libbloom#2]
During some experiments with this lib, I discover an undesirable correlation between filter size and collision number.

Filters tested for **0.0001** estimated FP accuracy (0.01%).
But real accuracy, in particular ranges of filter sizes, is far from given.

Example of accuracy  behavior near filter size **218793**:

![error-filtersize](https://cloud.githubusercontent.com/assets/95622/13554439/eb3855c6-e3b8-11e5-89bc-def80610adc9.png)

Globally, it looks much more strange:

[filters-statistics.txt](https://github.com/jvirkki/libbloom/files/160347/filters-statistics.txt)

![error-filtersize02](https://cloud.githubusercontent.com/assets/95622/13554543/946cdbd8-e3bb-11e5-88b2-663bfaa1029a.png)

For some filter sizes error jumps 70 times from 0.01% up to 0.7%

[Test code](https://gist.github.com/peko/48a4657a7c61f5b3b47d).

**Comment by jvirkki** [comment]
Thanks, I'll experiment with this when I get a moment.

**Comment by jvirkki** [comment]
Using the libbloom test I see similar behavior. I added a -G test option to generate data over a range of sizes. Here is the output where filter capacity ranges from 100K to 1M with a specified error of 0.001

![before](https://cloud.githubusercontent.com/assets/1110623/19376746/78835d42-9195-11e6-9cd9-a93109915a58.png)

As with the previous graph, the observed collision rate is at times far higher than 0.001

**Comment by jvirkki** [comment]
Looks like this was introduced by the buckets optimization included in PR #1. Reverting the buckets part of those changes results in collision rates like this (over the same interval and 0.001 error as above). Now the error is always well below 0.001:

![after](https://cloud.githubusercontent.com/assets/1110623/19376828/0d080878-9196-11e6-881e-336d659bd554.png)
