### ISSUE TITLE
Is the combined value after each hash operation evenly distributed in the bitmap?

### ISSUE THREAD

**Issue by WangTingZheng** [jvirkki/libbloom#21]
The statement
```c 
x = (a + i*b) % bloom->bits;
```
in `bloom.c` in function `bloom_check_add` uses two hash result and `i` to combine a new value to determine which bit should be set 1, so, is every x evenly distributed in the bitmap?

**Comment by ashtul** [comment]
Yes. It is a well-known optimization on bloom filter which allows calculating only two hashes regardless of the error rate.
