### ISSUE TITLE
How to implement delete?

### ISSUE THREAD

**Issue by etale-cohomology** [jvirkki/libbloom#26]
It seems **adds** work by looping over all hash functions and setting the corresponding bit in the bitbuffer assigned to each hash function.

How could **deletes** be implemented? Looping over all hash functions and zeroing the bit from the bitbuffer of every hash function?

Also why are there multiple hash functions? Why not just 1 hash function and 1 bit buffer?

**Comment by jvirkki** [comment]
Here's one intro to blom filters which might be helpful:
https://www.geeksforgeeks.org/bloom-filters-introduction-and-python-implementation/
