### ISSUE TITLE
-m32 gcc options seems not existing on armel which is 32-bit processor

### ISSUE THREAD

**Issue by rogers0** [jvirkki/libbloom#6]
I'm trying to make debian package. and now it compiles OK for i386 and amd64.
however, it fails on armel:

```
cc -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/arm-linux-gnueabi -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -O3 -m32 -std=c99 -fPIC -DBLOOM_VERSION=1.4 -I/<<PKGBUILDDIR>> -I/<<PKGBUILDDIR>>/murmur2 -c murmur2/MurmurHash2.c -o /<<PKGBUILDDIR>>/build/murmurhash2.o
cc -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/arm-linux-gnueabi -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -O3 -m32 -std=c99 -fPIC -DBLOOM_VERSION=1.4 -I/<<PKGBUILDDIR>> -I/<<PKGBUILDDIR>>/murmur2 -c bloom.c -o /<<PKGBUILDDIR>>/build/bloom.o
cc: error: unrecognized command line option '-m32'
cc: error: unrecognized command line option '-m32'
```
Full build log:
http://debomatic-armel.debian.net/distribution#experimental/libbloom/1.4-1~exp1/buildlog

**Comment by rogers0** [comment]
also fails on arm64:
```
cc -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/aarch64-linux-gnu -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -O3 -m64 -std=c99 -fPIC -DBLOOM_VERSION=1.4 -I/<<PKGBUILDDIR>> -I/<<PKGBUILDDIR>>/murmur2 -c murmur2/MurmurHash2.c -o /<<PKGBUILDDIR>>/build/murmurhash2.o
cc -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/aarch64-linux-gnu -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -O3 -m64 -std=c99 -fPIC -DBLOOM_VERSION=1.4 -I/<<PKGBUILDDIR>> -I/<<PKGBUILDDIR>>/murmur2 -c bloom.c -o /<<PKGBUILDDIR>>/build/bloom.o
cc: error: unrecognized command line option '-m64'
cc: error: unrecognized command line option '-m64'
```
http://debomatic-armhf.debian.net/distribution#experimental/libbloom/1.4-1~exp1/buildlog

**Comment by jvirkki** [comment]
In the 32 bit build, I assume you are setting MM in the environment to -m32, correct?

What option, if any, do you need to use on this platform to specify 32 or 64 bit to the compiler?

If an option is needed/available, set MM to the correct value and the existing Makefile should work as-is.

But if it is a case where no option is used, will need to change the Makefile to allow this given that currently it defaults to "-m64" if nothing is set.

**Comment by jvirkki** [comment]
Searching a bit, looks like there is no option available on that platform (but I don't have one to test). This means you'll need a way to override the default (-m64).

Set BITS to the string default (and don't set MM to anything) in your build environment. That way no option is passed to $(CC) which should do the right thing.

BITS=default make

Let me know if it worked.

**Comment by rogers0** [comment]
> In the 32 bit build, I assume you are setting MM in the environment to -m32, correct?

Yes.

> What option, if any, do you need to use on this platform to specify 32 or 64 bit to the compiler?

I'm not sure what do you mean.
Maybe you mean the bits used by int (integer) in C language?

> Set BITS to the string default (and don't set MM to anything) in your build environment. That way no option is passed to $(CC) which should do the right thing.
> BITS=default make

Removing MM setting in Makefile seems get built done on armel.
Setting BITS seems unnecessary.
I also didn't find any usage of BITS in code (by command: `grep -r BITS .`).

**Comment by jvirkki** [comment]
I mean, does the arm C compiler support or require any options (equivalent but different from -m32 and -m64) to instruct it to generate either 32 bit or 64 bit object files. After some web searching, it appears the answer is no (but I don't have a platform to test this).

BITS is not used in the code, only in the Makefile. Update your libbloom source to the latest to get these changes.

Then, do not set any value to MM in the debian build env. Instead, set BITS=default
This should fix your debian armel build.

**Comment by rogers0** [comment]
> BITS is not used in the code, only in the Makefile. Update your libbloom source to the latest to get these changes.

Sorry, I didn't use the latest commit.

> Then, do not set any value to MM in the debian build env. Instead, set BITS=default

Yes, "BITS=default make" builds well.

And I think maybe "BITS=default" applies on every platform on debian, so I add a local patch (don't expect it submit/get-merged to you upstream) to remove the MM setting block in Makefile:
 - https://github.com/rogers0/libbloom/blob/mentors/debian/patches/0002-Use-default-bits-of-compiler.patch
It seems it also builds well this way.

See build log on a few platform:
- http://debomatic-arm64.debian.net/distribution#experimental/libbloom/1.4-1~exp1/buildlog
- http://debomatic-armel.debian.net/distribution#experimental/libbloom/1.4-1~exp1/buildlog
- http://debomatic-armhf.debian.net/distribution#experimental/libbloom/1.4-1~exp1/buildlog
- http://debomatic-amd64.debian.net/distribution#experimental/libbloom/1.4-1~exp1/buildlog
- http://debomatic-i386.debian.net/distribution#experimental/libbloom/1.4-1~exp1/buildlog

Maybe -m64/-m32 is necessary for some platforms, but not debian.

**Comment by jvirkki** [comment]
You are correct in that specifying -m32/-m64 is often not necessary. It is only a problem on armel though, because its C compiler doesn't support it.

I do need the setting to be present at least for Solaris, which is why I made it configurable via the BITS var.

My recommendation is to not add this local patch 0002 removing BITS/MM.

Instead, just set BITS=default in the build environment. The end result is exactly the same so it doesn't really matter at the moment. However, future maintenance work will be reduced by avoiding local patches. If in the future I need to edit this BITS/MM section of the Makefile your local patch will break, causing you more work. If you set BITS=default and remove the patch, that potential problem is avoided.

But, that's up to you. Sounds like the build is working well either way so I'll close this issue. Let me know if you run into anything else.
