### ISSUE TITLE
unit test sometimes fails

### ISSUE THREAD

**Issue by rogers0** [jvirkki/libbloom#7]
I find the unit test sometimes (less than 20%, but maybe not accurate) fails.

Please find the build log on debian builldd:
  https://buildd.debian.org/status/fetch.php?pkg=libbloom&arch=amd64&ver=1.4-6&stamp=1494930635&raw=0

----- Running basic tests -----
----- basic -----
bloom at 0x7ffc4a988c30 not initialized!
bloom at 0x7ffc4a988c30 not initialized!
bloom at 0x7ffc4a988c30
 ->entries = 102
 ->error = 0.100000
 ->bits = 488
 ->bits per elem = 4.792529
 ->bytes = 61
 ->hash functions = 4
----- add_random(10, 0.100000, 10, 0, 1, 32, 1) -----
bloom at 0x7ffc4a988b20
 ->entries = 10
 ->error = 0.100000
 ->bits = 47
 ->bits per elem = 4.792529
 ->bytes = 6
 ->hash functions = 4
entries: 10, error: 0.100000, count: 10, coll: 2, error: 0.200000, bytes: 6
error: expected error 0.100000 but observed 0.200000
Makefile:124: recipe for target 'test' failed

**Comment by jvirkki** [comment]
The occasionally failing test was using a filter with a capacity of only 10. With so few bytes, sometimes more than the expected collisions would happen. Tiny sets are not a use case for bloom filters so changed the minimum size to 1000 (which is still too tiny in practice, but likely ok for testing).

**Comment by rogers0** [comment]
@jvirkki thanks!
