### ISSUE TITLE
Feature Request: upgrade to Murmurhash3

### ISSUE THREAD

**Issue by wongsyrone** [jvirkki/libbloom#9]
According to the original author,

>  which is the latest version in the series of MurmurHash functions - the new version is faster, more robust, and its variants can produce 32- and 128-bit hash values efficiently on both x86 and x64 platforms.

The source file can be found at https://github.com/aappleby/smhasher/blob/master/src/MurmurHash3.cpp

**Comment by wongsyrone** [comment]
Already done this by myself

**Comment by albertobsd** [comment]
@wongsyrone can you share a link to your work with this modifications that  you made?
